### ISSUE TITLE
Add Open JDK 9

### ISSUE THREAD

**Issue by yschimke** [michaelklishin/jdk_switcher#7]
In TravisCI, the package is available (points at an ea), but the jdk switcher fails.

```
jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer
```
